name: This is Regina
favicon: null
layout_spectrum: 0.50512
typography_spectrum: 1
title: This is Regina
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030b00'
    - '#39633f'
    - '#ffff00'
    - '#ffffff'
    - '#8fc265'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
