name: This is Regina
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26017
title: This is Regina
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8f6ff'
    - '#75b0e8'
    - '#110d0a'
    - '#4b504c'
    - '#c6b26e'
  brandStrength: 0
  lightness: 0.9815509791951627
  saturation: 0.5
  rhythmicContrast: 0.9708276332821697
purpose: []
