name: This is Regina
favicon: null
layout_spectrum: 0.24534
typography_spectrum: 0.26017
title: This is Regina
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f1f1'
    - '#333331'
    - '#83b7e2'
    - '#a51115'
    - '#34a41c'
  brandStrength: 0.5
  lightness: 0.9815509791951627
  saturation: 0.5
  rhythmicContrast: 0.9708276332821697
purpose: []
